### PR TITLE
Add Markdown parser to Project / Service Description + Field Dependency.Events

### PR DESCRIPTION
**Pull request by svenhartmann**
It should be possible to document consumed domain events e.g.

```dependencies:
  - reference: my-fancy--specification-service.events
    relationship: acl
    description: AMQP
    events: 
      - name: AssetCreated
      - name: AssetUpdated

### CODE REVIEW

**Comment by danielpoe** [comment]
Looks good thanks

**Comment by nxpthx** [comment]
@svenhartmann Any update on this?

**Comment by svenhartmann** [comment]
@nxpthx @danielpoe
Suggest changes commited. Maybe "ConsumesEvents" could be more suitable. I hope you both and all AOE People are still healthy :)

**Review by nxpthx — APPROVED** [review]

**Comment by nxpthx** [comment]
Will merge as soon as the pipeline stuff is done, so the history stays cleaner

**Pull request merged**
